add_newline = false
format = "$hostname$directory$git_branch$git_state$git_status$cmd_duration$character"

[hostname]
format = "[$hostname]($style) "

[directory]
style = "blue"
truncation_length = 3
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[$ahead_behind$stashed]($style) "
style = "cyan"
stashed = "â‰¡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[character]
success_symbol = "[â¯](bold green) "
error_symbol = "[ğŸ˜¿ â¯](bold red) "